//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieAdda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Moviee
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string Movie { get; set; }
        [Required]
        public string Actor { get; set; }
        [Required]
        public System.DateTime ReleasedDate { get; set; }
    }
}
